name: PHP 8.3

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v5

      - name: Composer Installation
        uses: php-actions/composer@v6

      - name: PHP 8.3+ Compatibility
        id: php
        uses: php-actions/composer@v6
        with:
          command: "test:compatibility:php"
